package com.devops.rest.error;

public enum ApiErrorCode {
    BAD_REQUEST,
    NOT_FOUND,
    REPOSITORY_NOT_FOUND,
    REFERENCE_NOT_FOUND,
    TAG_NOT_FOUND,
    EXTERNAL_AUTHENTICATION_FAILED,
    EXTERNAL_SERVICE_UNAVAILABLE,
    CONFIGURATION_UNREADABLE,
    UNEXPECTED_ERROR
}
